export const BOOK_NFT_ADDRESS = process.env.REACT_APP_BOOK_ADDRESS;
export const BOOKY_TOKEN_ADDRESS = process.env.REACT_APP_ERC20_ADDRESS;
export const MARKETPLACE_ADDRESS = process.env.REACT_APP_MARKETPLACE_ADDRESS;



